name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          approvalPrefix: approve-ci-
          errorAction: reject
          rejectionPrefix: reject-ci-
          repository: ${{ github.repository }}
          runId: ${{ github.run_id }}
          slackAppId: intentional-bad-value-see-tests-for-reason
          slackChannel: ${{ secrets.SLACK_CHANNEL }}
          slackHistoryLimit: '15'
          slackPollPause: '10000' # 10 seconds between polling requests
          slackPollTimeout: '300000' # 5 min timeout
          slackToken: ${{ secrets.SLACK_TOKEN }}
          timeoutAction: reject
